In [9]:
import pandas as pd
import matplotlib.pyplot as plt
date_cols = ['Gestartet', 'Beendet',"Monat (MM/JJJJ)"]
meineDaten= pd.read_csv("Alle-ladevorgänge-2022-03-16.csv", sep=";",encoding='latin-1',decimal=",", parse_dates=date_cols)
meineDaten['Ladepunkt'] = meineDaten['Ladepunkt'].replace(['DE*cem*E740796*001'],'Salzgitter 1')
meineDaten['Ladepunkt'] = meineDaten['Ladepunkt'].replace(['DE*cem*E740796*002'],'Salzgitter 2')
meineDaten['Ladepunkt'] = meineDaten['Ladepunkt'].replace(['DE*cem*E740796*003'],'Salzgitter 3')
meineDaten['Ladepunkt'] = meineDaten['Ladepunkt'].replace(['DE*cem*E740796*004'],'Salzgitter 4')

meineDaten['Ladepunkt'] = meineDaten['Ladepunkt'].replace(['DE*cem*E809189*001'],'WF Recht 1')
meineDaten['Ladepunkt'] = meineDaten['Ladepunkt'].replace(['DE*cem*E809189*002'],'WF Recht 2')

meineDaten['Ladepunkt'] = meineDaten['Ladepunkt'].replace(['DE*cem*EMLP1'],'WF Gebäude H 1') #EMLP
meineDaten['Ladepunkt'] = meineDaten['Ladepunkt'].replace(['DE*cem*EMLP2'],'WF Gebäude H 2')

meineDaten['Ladepunkt'] = meineDaten['Ladepunkt'].replace(['DE*cem*ESLP1'],'WF Gebäude H 3') #ESLP2
meineDaten['Ladepunkt'] = meineDaten['Ladepunkt'].replace(['DE*cem*ESLP2'],'WF Gebäude H 4')


####Leere Spalten löschen
meineDaten.drop('Stop-Grund', inplace=True, axis=1)
meineDaten.drop('Grund für die Auffälligkeit', inplace=True, axis=1)
meineDaten.drop('Kosten', inplace=True, axis=1)
meineDaten.drop('Provider', inplace=True, axis=1)
meineDaten.drop('Operator', inplace=True, axis=1)


meineDaten.head()

,Ladepunkt,Gestartet,Beendet,Monat (MM/JJJJ),Standzeit,Zählerstand Start (kWh,Zählerstand Ende (kWh),Verbrauch (kWh),Vertrag
0,Salzgitter 4,2022-03-16 11:06:00,2022-03-16 13:50:00,2022-03-16 13:50:00,9896,1805.556,1814.892,9.336,DE*CEM*C00560009
1,Salzgitter 4,2022-03-16 09:20:00,2022-03-16 10:02:00,2022-03-16 10:02:00,2522,1801.995,1805.556,3.561,DE*CEM*C00560009
2,WF Gebäude H 1,2022-03-16 08:22:00,2022-03-16 12:44:00,2022-03-16 12:44:00,15686,1285.290,1296.370,11.080,DE*CEM*C00555788
3,Salzgitter 3,2022-03-16 08:01:00,2022-03-16 11:10:00,2022-03-16 11:10:00,11321,5665.706,5687.539,21.833,DE*CEM*C00560009
4,WF Gebäude H 3,2022-03-16 07:55:00,2022-03-16 14:10:00,2022-03-16 14:10:00,22518,1103.820,1150.750,46.930,DE*CEM*C00552222

In [16]:
print("Anzahl der enthaltenen Datensätze: ", len(meineDaten))
#### Zeitumformen object-datetime
meineDaten['Gestartet'] = pd.to_datetime(meineDaten['Gestartet'])


meineDaten.dtypes

Anzahl der enthaltenen Datensätze:  2087

Ladepunkt                         object
Gestartet                 datetime64[ns]
Beendet                   datetime64[ns]
Monat (MM/JJJJ)           datetime64[ns]
Standzeit                          int64
Zählerstand Start (kWh           float64
Zählerstand Ende (kWh)           float64
Verbrauch (kWh)                  float64
Vertrag                           object
dtype: object